// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtufwxxjmnxnqcgsxjah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dWZ3eHhqbW54bnFjZ3N4amFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTk3MzMsImV4cCI6MjA2NjI3NTczM30.KebHYo8VsKcOh1H3rqlGZVAg_k2mS83AQoEVCCi0YlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});